version: "2.4"

services:
  frontend:
    depends_on:
      - backend
    image: node:18
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./renderer:/app
    command: sh -c "npm install && npm run dev"

  mysql:
    container_name: "mysql_database"
    image: mysql:8.0.31
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: db_example
    ports:
      - "3306:3306"

  # Uwaga! W przypadku błedu kontenera backendu
  # należy poczekać aż kontener mysql zacznie działać,
  # a następnie uruchomić kontener backednu jeszcze raz

  backend:
    depends_on:
      - mysql
    build:
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql_database:3306/db_example
      - spring.datasource.username=root
      - spring.datasource.password=
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - jwt.token.issuer="StudentCommunity"
      - jwt.token.signing.key="PrivateKey"
      - spring.mail.host=smtp.gmail.com
      - spring.mail.port=587
      - spring.mail.username=studentcommunityzpi@gmail.com
      - spring.mail.password=eisrazlpsvnbujhl
      - spring.mail.properties.mail.smtp.auth=true
      - spring.mail.properties.mail.smtp.starttls.enable=true
      - spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

volumes:
  mysql-data:
